-- MySQL Script generated by MySQL Workbench
-- Thu Jun 30 17:04:11 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categorias` (
  `idCategorias` INT NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategorias`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

-- Dumping data for table `brands`
--

LOCK TABLES `categorias` WRITE;
/*!40000 ALTER TABLE `categorias` DISABLE KEYS */;
INSERT INTO categorias (categoria)
VALUE ("musica"),
("trabajo"),
("salidas"),
("recordatorio"),
("estudio");
/*!40000 ALTER TABLE `categorias` ENABLE KEYS */;
UNLOCK TABLES;

-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `idUsuarios` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuarios`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

LOCK TABLES `usuarios` WRITE;
/*!40000 ALTER TABLE `usuarios` DISABLE KEYS */;
insert into usuarios (nombre, email)
value ("Vero", "vero@gmail.com"),
("Vane","vane@gmail.com"),
("Jacke","jacke@gmail.com"),
("Jorge","jorge@gmail.com"),
("Lili","lili@gmail.com"),
("Erika","erika@gmail.com"),
("Naian","naian@gmail.com"),
("Jhon","jhon@gmail.com"),
("Mona","mona@gmail.com"),
("Zeus","zeus@gmail.com");
/*!40000 ALTER TABLE `usuarios` ENABLE KEYS */;
UNLOCK TABLES;
-- -----------------------------------------------------
-- Table `mydb`.`notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`notas` (
  `idNotas` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `descripcion` LONGTEXT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `idUsuarios` INT NOT NULL,
  PRIMARY KEY (`idNotas`),
  CONSTRAINT `fk_Notas_Usuarios`
    FOREIGN KEY (`idUsuarios`)
    REFERENCES `mydb`.`usuarios` (`idUsuarios`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `fk_Notas_Usuarios_idx` ON `mydb`.`notas` (`idUsuarios` ASC) VISIBLE;

LOCK TABLES `notas` WRITE;
/*!40000 ALTER TABLE `notas` DISABLE KEYS */;
insert into notas (titulo, descripcion, idUsuarios)
value ("Estudiar", "Bases de datos", "1"),
("Estudiar", "React", "5"),
("Trabajar", "Reunión jefe", "10"),
("Estudiar", "HTML", "2"),
("Musiquita", "Descargar Shakira", "4"),
("Trabajar", "Revisar correos", "3"),
("Cita", "Cita medica", "8"),
("Clase Danza", "Clase de danza", "4"),
("Mural", "Buscar imagen mural", "3"),
("Fotografia", "Hacer trabajo", "4");
/*!40000 ALTER TABLE `notas` ENABLE KEYS */;
UNLOCK TABLES;
-- -----------------------------------------------------
-- Table `mydb`.`notas_has_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`notas_has_categorias` (
  `idNotas_categorias` INT NOT NULL auto_increment,
  `idNotas` INT NOT NULL,
  `idCategorias` INT NOT NULL,
  PRIMARY KEY (`idNotas_categorias`),
  CONSTRAINT `fk_Notas_has_Categorias_Categorias1`
    FOREIGN KEY (`idCategorias`)
    REFERENCES `mydb`.`categorias` (`idCategorias`),
  CONSTRAINT `fk_Notas_has_Categorias_Notas1`
    FOREIGN KEY (`idNotas`)
    REFERENCES `mydb`.`notas` (`idNotas`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `fk_Notas_has_Categorias_Categorias1_idx` ON `mydb`.`notas_has_categorias` (`idCategorias` ASC) VISIBLE;

CREATE INDEX `fk_Notas_has_Categorias_Notas1_idx` ON `mydb`.`notas_has_categorias` (`idNotas` ASC, `idNotas_categorias` ASC) VISIBLE;

LOCK TABLES `notas_has_categorias` WRITE;
/*!40000 ALTER TABLE `notas_has_categorias` DISABLE KEYS */;
INSERT INTO notas_has_categorias (idNotas, idCategorias)
value ("2", "5"),
("3", "2"),
("4", "5"),
("5", "1"),
("6", "2"),
("7", "3"),
("8", "4"),
("9", "4"),
("10", "5");
/*!40000 ALTER TABLE `notas_has_categorias` ENABLE KEYS */;
UNLOCK TABLES;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



